# Generated by Django 3.2.9 on 2021-11-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='task_name',
        ),
    ]
