# Generated by Django 3.2.9 on 2021-11-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment4', '0002_rename_task_todo_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
